# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

guest = User.create!(username: "guest", password: "password", fname: "Guest", lname: "lname");
jhauf = User.create!(username: "jhauf", password: "wGzbBuWq", fname: "Jane", lname: "Hauf");
jallan = User.create!(username: "jallan", password: "n86uVRe9", fname: "Jasmine", lname: "Allan");
jalsop = User.create!(username: "jalsop", password: "8YfgyBZB", fname: "Jennifer", lname: "Alsop");
janderson = User.create!(username: "janderson", password: "kncWvUsQ", fname: "Jessica", lname: "Anderson");
jarnold = User.create!(username: "jarnold", password: "ph8M6gXC", fname: "Joan", lname: "Arnold");
javery = User.create!(username: "javery", password: "uqpuKATG", fname: "Joanne", lname: "Avery");
jbailey = User.create!(username: "jbailey", password: "uZLbjesG", fname: "Julia", lname: "Bailey");
kbaker = User.create!(username: "kbaker", password: "MeKnEAUh", fname: "Karen", lname: "Baker");
kball = User.create!(username: "kball", password: "dgRepHE2", fname: "Katherine", lname: "Ball");
kbell = User.create!(username: "kbell", password: "nZMACvAn", fname: "Kimberly", lname: "Bell");
nberry = User.create!(username: "nberry", password: "2YNqrf9B", fname: "Nicholas", lname: "Berry");
oblack = User.create!(username: "oblack", password: "9JFZRyeT", fname: "Oliver", lname: "Black");
odaviszon = User.create!(username: "odaviszon", password: "Kq3ysKPg", fname: "Owen", lname: "Daviszon");
pbond = User.create!(username: "pbond", password: "J5uy7SXA", fname: "Paul", lname: "Bond");
pbower = User.create!(username: "pbower", password: "G3Re7EZ6", fname: "Peter", lname: "Bower");
pbrown = User.create!(username: "pbrown", password: "vQ2Qc9p3", fname: "Phil", lname: "Brown");
pbuckland = User.create!(username: "pbuckland", password: "jXhLb8XS", fname: "Piers", lname: "Buckland");
rburgess = User.create!(username: "rburgess", password: "bD47Udm9", fname: "Richard", lname: "Burgess");
rbutler = User.create!(username: "rbutler", password: "eYRmp7Ks", fname: "Robert", lname: "Butler");
rcameron = User.create!(username: "rcameron", password: "Qc3DxPWL", fname: "Ryan", lname: "Cameron");


Campaign.create!(name: "Monty's Deli", goal_amt: "50000", current_amt: "45000", description: "An authentic Jewish delicatessen open seven days a week, where traditional recipes are made expertly in house with great love and care.", end_date: "2017/05/15", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478463645/montys_uxvsqs.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488377/monty_s_deli_juqsqj.png", campaigner_id: 20);
Campaign.create!(name: "ChocAmo Cookie Cups | Sip. Bite. Feed Your Soul.", goal_amt: "18000", current_amt: "9535", description: "Join the snack time revolution and experience everyone's favorite childhood dessert with a modern twist! #loveatfirstbite", end_date: "2017/08/26", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478466148/cookie_sxw8os.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488379/chocamo_irxxoy.png", campaigner_id: 5);
Campaign.create!(name: "Comme Chez Moi by Minoofi", goal_amt: "2299", current_amt: "2100", description: "Minoofi Bakery's cookbook full of recipes to entertain your nearest and dearest with. Brunch, Afternoon Tea, Cocktail Hour & Party.", end_date: "2017/04/01", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478489575/minoofibakery_lwunfy.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478489501/minofibakery_hqfokj.jpg", campaigner_id: 6);
Campaign.create!(name: "House Cocktail Journal", goal_amt: "15000", current_amt: "17000", description: "A stunning, hardback, water-resistant journal for recording cocktail recipes. Space for over 150 drinks, separated by spirit.", end_date: "2017/08/15", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478464278/cocktail_ttuikr.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488360/cocktail_d6luok.jpg", campaigner_id: 19);
campaign3 = Campaign.create!(name: "Ogre Sauce - All-Purpose Craft BBQ Sauce", goal_amt: 6000, current_amt: 20069, description: "Tastes great on everything like ribs, wings, salmon, pizza, burgers, tofu, oysters, pretzels, steak, grilled veggies, pineapple, eggs.", end_date: "2016/7/12", video_url: 'http://res.cloudinary.com/dps0ohgkp/video/upload/v1478463570/ogre_pexyyi.mp4', picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488376/ogresauce_apslmq.jpg", campaigner_id: 4);
Campaign.create!(name: "When London meets Berlin for brünch", goal_amt: "12000", current_amt: "3000", description: "From pop up to permanent - We are opening London's first Berlin brünch Cafe in London Fields!", end_date: "2017/05/10", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478461497/london_meets_berlin_pjb6y0.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478489630/berlin_kyhffh.jpg", campaigner_id: 2);
Campaign.create!(name: "Pies Are Awesome - Pie Guides", goal_amt: "1492", current_amt: "11416", description: "Make your first pie an epic pie with the world's only Pie Guides", end_date: "2017/06/20", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478467638/pieguides_wfwpm1.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488377/pies_l8je47.jpg", campaigner_id: 6);
Campaign.create!(name: "Food for All: Help, Save & Eat", goal_amt: "50000", current_amt: "10000", description: "An app that reduces food waste by allowing you to buy food that restaurants did not sell by the end of the day, up to 80% cheaper.", end_date: "2017/04/19", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478465340/foodforall_hjbmjr.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488363/foodforall_fvmpdx.jpg", campaigner_id: 18);
Campaign.create!(name: "The Palate Deck: Playing Cards for Beer Tasting", goal_amt: "30000", current_amt: "9000", description: "Playing cards that offer beer information and casual tasting guidance for the many conversations that happen over beer.", end_date: "2017/05/01", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478467829/palettedeck_lmslj0.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478489131/palatedeck_w0mdy5.jpg", campaigner_id: 17);
Campaign.create!(name: "The Rwanda Craft Brewery Project", goal_amt: "70000", current_amt: "30000", description: "The Rwanda Craft Brewery Project", end_date: "2017/03/06", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478465837/rwanda_cincce.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488378/rwanda_kh2py0.jpg", campaigner_id: 7)
Campaign.create!(name: "A LoveLee Kitchen", goal_amt: "35000", current_amt: "25000", description: "We are building a LoveLee kitchen to support our family, carb love, and community.... in our backyard.", end_date: "2017/08/01", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478465384/aloveleekitchen_lywlkz.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478489347/lovelee_ap0kln.png", campaigner_id: 8);
Campaign.create!(name: "Benji's Farm - Plant-Powered Organic Dog Treats", goal_amt: "12000", current_amt: "2000", description: "Your dog deserves more than just a tasty snack! Discover how our treats harness the Power of Plants to help support doggy wellness.", end_date: "2017/02/22", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478467687/dogtreat_bqijhk.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488362/dogtreat_qu2s8m.jpg", campaigner_id: 16);
campaign1 = Campaign.create!(name: "Caramia Caramels", goal_amt: 10000, current_amt: 11000, description: "We are two best friends/sisters whose dream is to share our buttery, smooth, melt-in-your-mouth caramels with you!", end_date: "2016/12/1", video_url: 'http://res.cloudinary.com/dps0ohgkp/video/upload/v1478461156/caramia_lk6rlc.mp4', picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478490371/caramia_gikojs.jpg", campaigner_id: 3);
Campaign.create!(name: "CHiP Smart Cookie Oven—Fresh Cookies in Under 10 Minutes", goal_amt: "100000", current_amt: "34000", description: "The CHiP Smart Cookie Oven will bake perfect gourmet cookies in under 10 minutes.", end_date: "2017/02/06", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478465336/chipsmartcookieoven_ldy4q5.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488421/smartcookie_y3nbdk.jpg", campaigner_id: 9);
Campaign.create!(name: "Perfect Cookware for Everyone. Handcrafted in the USA.", goal_amt: "43000", current_amt: "30000", description: "Marie + Merrill offers exceptional American-made cookware at a fair, transparent price.", end_date: "2017/04/07", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478484489/cookware_wk3ogr.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488379/cookware_jpvsa5.png", campaigner_id: 10);
Campaign.create!(name: "Shiraz the Cookbook", goal_amt: "6800", current_amt: "1300", description: "In Shiraz, traditional and modern family recipes tell a story of inherited love through delicious Persian comfort food", end_date: "2017/03/16", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478484753/shiraz_cd1idh.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488378/shiraz_q4rzlm.jpg", campaigner_id: 11);
Campaign.create!(name: "Earnest Brew Works", goal_amt: "10000", current_amt: "6700", description: "Earnest Brew Works is brewery and taproom located in Toledo, Ohio. Brewer-owned and operated, EBW will open in November", end_date: "2017/03/15", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478466052/earnestbrew_bcy6sa.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478489272/earnest_tey2ez.jpg", campaigner_id: 15);
Campaign.create!(name: "MONK’S vegan DELICATESSEN and KITCHEN", goal_amt: "50000", current_amt: "20000", description: "Support our mission to bring great tasting, fresh food to Brooklyn at NY’s premier vegan delicatessen! #EatAtMonks #freshfoodtastesgood", end_date: "2017/06/22", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478466045/monk_s_maacsz.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478488368/monks_xeoq0n.jpg", campaigner_id: 14);
Campaign.create!(name: "Tripp's Tipples - Rock and Rye and other spirit infusions", goal_amt: "3600", current_amt: "4150", description: "Creating a line of infusions that will take your spirits to the next level. We invite you to try our first...the Rock and Rye.", end_date: "2017/06/13", video_url: "http://res.cloudinary.com/dps0ohgkp/video/upload/v1478465650/rockandrye_solabj.mp4", picture_url: "http://res.cloudinary.com/dps0ohgkp/image/upload/v1478489637/trippstripples_uxhq1a.png", campaigner_id: 13);
